sonar.projectKey=Ella-rep_running-tracker
sonar.organization=ella-rep
sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=var/coverage/clover.xml
sonar.exclusions=vendor/**,public/bundles/**,var/**,docker/**,Dockerfile,docker-compose.yml,docker-compose.*.yml,compose.override.yaml,install_service.sh
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=tests/**
