<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260325000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema: users, run_logs, races, plan_progress, plans, plan_details';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE users (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            username VARCHAR(64) NOT NULL,
            password VARCHAR(255) NOT NULL,
            roles JSON NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9F85E0677 ON users (username)');

        $this->addSql('CREATE TABLE run_logs (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            date VARCHAR(10) NOT NULL,
            km DOUBLE PRECISION DEFAULT NULL,
            duration VARCHAR(12) DEFAULT NULL,
            allure VARCHAR(8) DEFAULT NULL,
            gap VARCHAR(8) DEFAULT NULL,
            dplus INT DEFAULT NULL,
            bpm INT DEFAULT NULL,
            run_type VARCHAR(16) DEFAULT NULL,
            notes TEXT DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_6C719978A76ED395 ON run_logs (user_id)');
        $this->addSql('ALTER TABLE run_logs ADD CONSTRAINT fk_run_logs_user
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE races (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            name VARCHAR(128) NOT NULL,
            date VARCHAR(10) NOT NULL,
            distance VARCHAR(16) DEFAULT NULL,
            objective VARCHAR(12) DEFAULT NULL,
            result VARCHAR(12) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_5DBD1EC9A76ED395 ON races (user_id)');
        $this->addSql('ALTER TABLE races ADD CONSTRAINT fk_races_user
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE plan_progress (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            plan_key VARCHAR(32) NOT NULL,
            session_index INT NOT NULL,
            done BOOLEAN NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_plan_progress_user_key_idx ON plan_progress (user_id, plan_key, session_index)');
        $this->addSql('CREATE INDEX idx_plan_progress_user ON plan_progress (user_id)');
        $this->addSql('ALTER TABLE plan_progress ADD CONSTRAINT fk_plan_progress_user
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE plans (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            name VARCHAR(64) NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_plans_user_name ON plans (user_id, name)');
        $this->addSql('CREATE INDEX IDX_PLANS_USER ON plans (user_id)');
        $this->addSql('ALTER TABLE plans ADD CONSTRAINT fk_plans_user
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE plan_details (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            plan_id INT NOT NULL,
            position INT NOT NULL,
            sem INT DEFAULT NULL,
            session_date DATE DEFAULT NULL,
            format TEXT NOT NULL,
            pe VARCHAR(10) DEFAULT NULL,
            total_min INT DEFAULT NULL,
            is_optional BOOLEAN NOT NULL,
            is_done BOOLEAN NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_plan_details_user_plan_pos ON plan_details (user_id, plan_id, position)');
        $this->addSql('CREATE INDEX idx_plan_details_plan ON plan_details (plan_id)');
        $this->addSql('ALTER TABLE plan_details ADD CONSTRAINT fk_plan_details_user
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plan_details ADD CONSTRAINT fk_plan_details_plan
            FOREIGN KEY (plan_id) REFERENCES plans (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE plan_details DROP CONSTRAINT fk_plan_details_plan');
        $this->addSql('ALTER TABLE plan_details DROP CONSTRAINT fk_plan_details_user');
        $this->addSql('ALTER TABLE plans DROP CONSTRAINT fk_plans_user');
        $this->addSql('ALTER TABLE run_logs DROP CONSTRAINT fk_run_logs_user');
        $this->addSql('ALTER TABLE races DROP CONSTRAINT fk_races_user');
        $this->addSql('ALTER TABLE plan_progress DROP CONSTRAINT fk_plan_progress_user');
        $this->addSql('DROP TABLE plan_details');
        $this->addSql('DROP TABLE plans');
        $this->addSql('DROP TABLE plan_progress');
        $this->addSql('DROP TABLE run_logs');
        $this->addSql('DROP TABLE races');
        $this->addSql('DROP TABLE users');
    }
}
