parameters:
    geo_key:  '%env(GEO_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            - geoKey: '%geo_key%'

    App\Controller\:
        resource: '../src/Controller/'

    App\Service\:
        resource: '../src/Service/'

    App\OpenApi\PasswordResetOpenApiFactory:
        decorates: 'api_platform.openapi.factory'
        arguments:
            - '@App\OpenApi\PasswordResetOpenApiFactory.inner'
        autoconfigure: false

    App\Service\LocService:
        arguments:
            - '%geo_key%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Controller/'
            - '../src/Service/'
            - '../src/Entity/'
            - '../src/Kernel.php'
